const EVENTS = {
    GOOGLE_LOGIN: 'GOOGLE_LOGIN',
    GET_SCREEN_SOURCE: 'GET_SCREEN_SOURCE',
    STOP_SHARE_SCREEN: 'STOP_SHARE_SCREEN',
    SHARE_SCREEN: 'SHARE_SCREEN',
    GOOGLE_LOGIN_SUCCESS: 'GOOGLE_LOGIN_SUCCESS',
    SHARE_SCREEN_SUCCESS: 'SHARE_SCREEN_SUCCESS',
    SEND_DOODLE_SHARE_SCREEN: 'SEND_DOODLE_SHARE_SCREEN',
}

module.exports = { EVENTS }