export const ELECTRON_EVENTS = {
    GOOGLE_LOGIN: 'GOOGLE_LOGIN',
    GET_SCREEN_SOURCE: 'GET_SCREEN_SOURCE',
    SHARE_SCREEN: 'SHARE_SCREEN',
    GOOGLE_LOGIN_SUCCESS: 'GOOGLE_LOGIN_SUCCESS',
};
  